authenticate/urls.py
# coding=utf-8
"""gleam URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include, patterns
from django.contrib import admin
from diagnostic import urls as diagnostic_urls
from authenticate import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='profile'),
]

chat/urls.py
# coding=utf-8
from django.conf.urls import url
from chat import views

urlpatterns = [
    url(r'^$', views.ChatView.as_view(), name='chat_room'),
]

core/urls.py
# coding=utf-8
"""
URLs for core app
"""

from django.conf.urls import url
from core import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^progress/check/$', views.progress_delay, name='progress_check'),
    url(r'^patient/$', views.PatientHomeView.as_view(), name='patient_home'),
    url(r'^therapist/$', views.therapist_home, name='therapist_home'),
    url(r'^therapist/patient/$', views.patient_list, name='patient_list'),
    url(r'^therapist/patient/(?P<patient_id>[0-9]+)/$', views.patient_list, name='patient_profile'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
]

gleam/urls.py
# coding=utf-8
"""gleam URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from diagnostic import urls as diagnostic_urls
from authenticate import urls as auth_urls
from core import urls as core_urls
from journal import urls as journal_urls
from chat import urls as chat_urls
from tasks import urls as tasks_urls

urlpatterns = [
    url(r'', include(core_urls, namespace='core')),
    url(r'^users/', include(auth_urls, namespace='authenticate')),
    url(r'^survey/', include(diagnostic_urls, namespace='diagnostic')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^qa/', include(qa_urls, namespace='qa')),
    # url(r'^case/', include(cc_urls, namespace='case')),
    url(r'^journal/', include(journal_urls, namespace='journal')),
    url(r'^chat/', include(chat_urls, namespace='chat')),
    url(r'^tasks/', include(tasks_urls, namespace='tasks'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/urls.py
# coding=utf-8
from django.conf.urls import url
from journal import views

urlpatterns = [
    url(r'^$', views.entry, name='entry'),
    url(r'^history/$', views.list_view, name='history'),
    url(r'^entry/$', views.entry, name='entry'),
    url(r'^entry/(?P<entry_id>[0-9]+)/$', views.view_entry, name='view_entry'),
    url(r'^words/$', views.word_list, name='words'),
]

qa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from qa import views

from django.conf.urls import url, include
from django.contrib.auth.models import User
from qa.models import Question, Tag
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

class QuestionSerializer(serializers.HyperlinkedModelSerializer):
    tags = serializers.SlugRelatedField(
        many=True,
        read_only=True,
        slug_field='slug'
     )
    class Meta:
        model = Question
        fields = ('id', 'pub_date', 'question_text', 'tags', 'views')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'api/users', UserViewSet)
router.register(r'api/questions', QuestionViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^q/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^answer/(?P<question_id>\d+)/$', views.answer, name='answer'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^add/$', views.add, name='add'),
    url(r'^answer/$', views.add_answer, name='add_answer'),
    url(r'^vote/(?P<user_id>\d+)/(?P<answer_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.vote, name='vote'),
    url(r'^comment/(?P<answer_id>\d+)/$', views.comment, name='comment'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tag/(?P<tag>\w+)/$', views.tag, name='tag'),
    url(r'^thumb/(?P<user_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.thumb, name='thumb'),
    url('^markdown/', include( 'django_markdown.urls')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    #url('^forgot/', include('password_reset.urls')),
]

core/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User


class ProgressIssue(models.Model):
    """
    Model to gather stats on issues that hinder a user's progress in their regime
    """
    user = models.ForeignKey(User)

    work = models.BooleanField(default=False, blank=True)
    access_to_computer = models.BooleanField(default=False, blank=True)
    time_commitment = models.BooleanField(default=False, blank=True)
    motivation = models.BooleanField(default=False, blank=True)
    forgetfulness = models.BooleanField(default=False, blank=True)
    tired = models.BooleanField(default=False, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)

    class Meta(object):
        unique_together = ('user', 'created_on',)

core/forms.py
# coding=utf-8

from core import models
from django import forms


class ProgressIssueForm(forms.ModelForm):
    class Meta(object):
        model = models.ProgressIssue
        exclude = ('user',)

core/views.py
# coding=utf-8
import json
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.utils.timezone import datetime
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from core import forms
from tasks.models import MainTask
from journal.models import Entry, Note
from authenticate.models import Client

MAX_ROWS = 5


def index(request):
    return render(request, 'index.html', {})


@login_required()
def progress_delay(request):
    if request.method == 'POST':
        progress_issue = forms.ProgressIssueForm(request.POST)
        if progress_issue.is_valid():
            progress_issue = progress_issue.save(commit=False)
            progress_issue.user = User.objects.get(id=request.user.id)
            progress_issue.save()
            if request.GET.get('courses', None) is not None:
                return HttpResponseRedirect(reverse('case:start_course'))
            else:
                print request.GET
                return HttpResponseRedirect('/')
        else:
            return render(request, 'core/progress-delay.html', {'errors': progress_issue.errors})
    else:
        return render(request, 'core/progress-delay.html', {})


@login_required()
def therapist_home(request):
    # TODO order clients by last appointment/different metric
    return render(request, 'core/therapist-dashboard/content-tp-dash.html', {
        'notes': Note.objects.filter(therapist__user_profile__user_id=request.user.id)[:MAX_ROWS],
        'clients': Client.objects.filter(therapist__user_profile__user_id=request.user.id)[:MAX_ROWS]
    })


def landing(request):
    return render(request, 'core/landing/landing.html', {})


class PatientHomeView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'core/dashboard/patient-home.html',
                      {'tasks': MainTask.objects.filter(patient__user_id=request.user.id, completed=False).order_by(
                          'created')[:MAX_ROWS],
                       'journals': Entry.objects.filter(user_id=request.user.id).order_by('-created')[:MAX_ROWS]
                       })

    @method_decorator(login_required)
    def post(self, request):
        if 'toggle' in request.POST:
            task = MainTask.objects.get(id=int(request.POST['task']), patient__user_id=request.user.id)
            if task.completed:
                task.completed = False
            else:
                task.completed = True
            task.completed_on = datetime.now()
            task.save()
            tasks = MainTask.objects.filter(patient__user_id=request.user.id, completed=False).order_by('created')[
                    :MAX_ROWS]
            return HttpResponse(json.dumps(
                {'state': task.completed,
                 'tasks': [task.as_dict() for task in tasks]
                 }))


@login_required()
def dashboard(request):
    if request.user.userprofile.is_therapist:
        return therapist_home(request)
    else:
        return PatientHomeView.as_view()(request)


@login_required()
def patient_list(request):
    client_list = Client.objects.filter(therapist__user_profile__user_id=request.user.id)
    paginator = Paginator(client_list, MAX_ROWS)
    try:
        clients = paginator.page(request.GET.get('page'))
    except PageNotAnInteger:
        clients = paginator.page(1)
    except EmptyPage:
        clients = paginator.page(paginator.num_pages)
    return render(request, 'therapist/patient-list.html',
                  {'clients': clients,
                   'paginator': paginator})

templates/core/therapist-dashboard/base-therapist-dash.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gleam - {% block title %}{% endblock %}</title>
    <script type="application/javascript" src="{% static 'js/kill-iframe.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/therapist-dash/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/therapist-dash/therapist_notes.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    {% block head %}{% endblock %}

    <!-- HTML5 Shiv -->
    <script src="{% static 'js/html5shiv.min.js' %}"></script>
</head>
<body>


<div class="main-wrapper">
    <div class="app" id="app">
        <header class="header">
            <div class="header-block hidden-sm-down hidden-md-down">
                <div class="brand">
                    <div class="logo-124"
                         style="background-image: url('{% static 'images/gleam-124.png' %}')"></div>
                </div>
            </div>
            <div class="header-block header-block-collapse hidden-lg-up">
                <button class="collapse-btn" id="sidebar-collapse-btn"><i class="fa fa-bars"></i></button>
            </div>
            <div class="header-block header-block-nav">
                <ul class="nav-profile">
                    <li class="notifications">
                        <a href="" data-toggle="dropdown"> <i class="fa fa-bell-o"></i></a>
                    </li>
                    <li class="profile dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            <div class="img"
                                 style="background-image: url('{{ request.user.userprofile.picture.url }}');"></div>
                            <span class="name">{{ request.user.first_name }}</span> </a>
                        <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'authenticate:profile' request.user.id %}"> <i
                                    class="fa fa-user icon"></i> Profile </a>
                            <a class="dropdown-item" href="#"> <i class="fa fa-bell icon"></i> Notifications </a>
                            <a class="dropdown-item" href="#"> <i class="fa fa-gear icon"></i> Settings </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"
                               href="{% url 'authenticate:logout' %}?next={{ request.path | urlencode }}"> <i
                                    class="fa fa-power-off icon"></i> Logout </a>
                        </div>
                    </li>
                </ul>
            </div>
        </header>
        <aside class="sidebar">
            <div class="sidebar-container">
                <div class="sidebar-header"></div>
                <nav class="menu">
                    <ul class="nav mentismenu" id="sidebar-menu">
                        <li>
                            <div class="side-bar-profile"
                                 style="background-image: url('{{ request.user.userprofile.picture.url }}');"></div>
                        </li>
                        <li id="homeSidebar">
                            <a href="{% url 'core:therapist_home' %}"> <i class="fa fa-home"></i> Dashboard </a>
                        </li>
                        <li id="calendarSidebar">
                            <a href="#"> <i class="fa fa-calendar"></i> Appointments</a>
                        </li>
                        <li id="chatSidebar">
                            <a href="{% url 'chat:chat_room' %}"> <i class="fa fa-comment"></i> Chat</a>
                        </li>
                        <li id="patientsSidebar">
                            <a href="{% url 'core:patient_list' %}"> <i class="fa fa-group"></i> Patients</a>
                        </li>
                        <li id="notesSidebar">
                            <a href="{% url 'journal:entry' %}"> <i class="fa fa-sticky-note-o"></i> Notes</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="sidebar-overlay" id="sidebar-overlay"></div>
        {#    main content #}
        <article class="content dashboard-page">
            {% block body %}{% endblock %}
        </article>
        <footer class="footer">
        </footer>
    </div>
</div>

<script type="application/javascript" src="{% static 'js/jquery-latest.js' %}"></script>
<script type="application/javascript" src="{% static 'js/tether.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="application/javascript" src="{% static 'js/jq.redirect.js' %}"></script>
<script type="application/javascript" src="{% static 'js/escape-html.js' %}"></script>
<script type="application/javascript" src="{% static 'js/dashboard/animations.js' %}"></script>
<script type="application/javascript" src="{% static 'js/therapist-dash/metisMenu.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/therapist-dash/therapist_notes.js' %}"></script>
<script type="application/javascript" src="{% static 'js/base-init.js' %}"></script>
{% block js_scripts %}
{% endblock %}
</body>
</html>

templates/core/therapist-dashboard/content-tp-dash.html
{% extends 'core/therapist-dashboard/base-therapist-dash.html' %}
{% load static from staticfiles %}
{% block title %}Therapist Dashboard{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="row">

        <div class="col-xl-6">
            <div class="card sameheight-item sales-breakdown" data-exclude="xs,sm,lg">
                <div class="card-header bordered">
                    <div class="header-block">
                        <h3 class="title">
                            Notifications
                        </h3></div>
                </div>
                <div class="card-block">
                    <div class="dashboard-sales-breakdown-chart" id="dashboard-sales-breakdown-chart"></div>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card sameheight-item sales-breakdown" data-exclude="xs,sm,lg">
                <div class="card-header bordered">
                    <div class="header-block">
                        <h3 class="title">
                            Appointments
                        </h3> <a href="" class="btn btn-primary btn-sm rounded">
                        Add new
                    </a></div>
                </div>
                <div class="card-block">
                    <div class="dashboard-sales-breakdown-chart" id="dashboard-sales-breakdown-chart"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-xl-6">
            <div class="card sameheight-item items" data-exclude="xs,sm,lg">
                <div class="card-header bordered">
                    <div class="header-block">
                        <h3 class="title">
                            Patients
                        </h3> <a href="" class="btn btn-primary btn-sm rounded">
                        Add new
                    </a></div>
                </div>
                <ul class="item-list striped">
                    <li class="item item-list-header hidden-sm-down">
                        <div class="item-row">
                            <div class="item-col item-col-header fixed item-col-img xs"></div>
                            <div class="item-col item-col-header item-col-title">
                                <div><span>Name</span></div>
                            </div>
                            <div class="item-col item-col-header item-col-date">
                                <div><span>Messages</span></div>
                            </div>
                        </div>
                    </li>
                    {% for client in clients %}
                        <li class="item">
                            <div class="item-row">
                                <div class="item-col fixed item-col-img xs">
                                    <a href="">
                                        <div class="item-img xs rounded"
                                             style="background-image: url({{ client.user_profile.picture.url }})"></div>
                                    </a>
                                </div>
                                <div class="item-col item-col-title no-overflow">
                                    <div>
                                        <a href="" class="">
                                            <h4 class="item-title no-wrap">
                                                {{ client.user_profile.user.first_name }} {{ client.user_profile.user.last_name }}
                                            </h4></a>
                                    </div>
                                </div>
                                <div class="item-col item-col-date">
                                    <div class="item-heading">Last Appointment</div>
                                    <div> 21 SEP 10:45</div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card sameheight-item items" data-exclude="xs,sm,lg">
                <div class="card-header bordered">
                    <div class="header-block">
                        <h3 class="title">
                            Notes
                        </h3> <a href="" class="btn btn-primary btn-sm rounded">
                        Add new
                    </a></div>
                </div>
                <ul class="item-list striped">
                    <li class="item item-list-header hidden-sm-down">
                        <div class="item-row">
                            <div class="item-col item-col-header item-col-title">
                                <div><span>Title</span></div>
                            </div>
                            <div class="item-col item-col-header item-col-date">
                                <div><span>Date Posted</span></div>
                            </div>
                        </div>
                    </li>
                    {% for note in notes %}
                        <li class="item">
                            <div class="item-row">
                                <div class="item-col item-col-title no-overflow">
                                    <div>
                                        <a href="{% url 'journal:view_entry' note.id %}" class="">
                                            <h4 class="item-title no-wrap">
                                                {{ note.title }}
                                            </h4></a>
                                    </div>
                                </div>
                                <div class="item-col item-col-date">
                                    <div class="item-heading">Published</div>
                                    <div>{{ note.created_on_strformat }}</div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block js_scripts %}
    <script type="application/javascript">
        $(document).ready(function () {
            $('#homeSidebar').addClass('active');
        });
    </script>
{% endblock %}

templates/core/therapist-dashboard/therapist_header.html
{% load static from staticfiles %}
<header class="header">
    <div class="header-block hidden-sm-down hidden-md-down">
        <div class="brand">
            <div class="logo-124"
                 style="background-image: url('{% static 'images/gleam-124.png' %}')"></div>
        </div>
    </div>
    <div class="header-block header-block-collapse hidden-lg-up">
        <button class="collapse-btn" id="sidebar-collapse-btn"><i class="fa fa-bars"></i></button>
    </div>
    <div class="header-block header-block-nav">
        <ul class="nav-profile">
            <li class="notifications">
                <a href="" data-toggle="dropdown"> <i class="fa fa-bell-o"></i></a>
            </li>
            <li class="profile dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">
                    <div class="img"
                         style="background-image: url('{{ request.user.userprofile.picture.url }}');"></div><span
                        class="name">{{ request.user.first_name }}</span> </a>
                <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" href="{% url 'authenticate:profile' request.user.id %}"> <i
                            class="fa fa-user icon"></i> Profile </a>
                    <a class="dropdown-item" href="#"> <i class="fa fa-bell icon"></i> Notifications </a>
                    <a class="dropdown-item" href="#"> <i class="fa fa-gear icon"></i> Settings </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item"
                       href="{% url 'authenticate:logout' %}?next={{ request.path | urlencode }}"> <i
                            class="fa fa-power-off icon"></i> Logout </a>
                </div>
            </li>
        </ul>
    </div>
</header>