gleam/urls.py
# coding=utf-8
"""gleam URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from diagnostic import urls as diagnostic_urls
from authenticate import urls as auth_urls
from core import urls as core_urls
from journal import urls as journal_urls
from chat import urls as chat_urls
from tasks import urls as tasks_urls

urlpatterns = [
    url(r'', include(core_urls, namespace='core')),
    url(r'^users/', include(auth_urls, namespace='authenticate')),
    url(r'^survey/', include(diagnostic_urls, namespace='diagnostic')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^qa/', include(qa_urls, namespace='qa')),
    # url(r'^case/', include(cc_urls, namespace='case')),
    url(r'^journal/', include(journal_urls, namespace='journal')),
    url(r'^chat/', include(chat_urls, namespace='chat')),
    url(r'^tasks/', include(tasks_urls, namespace='tasks'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from qa import views

from django.conf.urls import url, include
from django.contrib.auth.models import User
from qa.models import Question, Tag
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

class QuestionSerializer(serializers.HyperlinkedModelSerializer):
    tags = serializers.SlugRelatedField(
        many=True,
        read_only=True,
        slug_field='slug'
     )
    class Meta:
        model = Question
        fields = ('id', 'pub_date', 'question_text', 'tags', 'views')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'api/users', UserViewSet)
router.register(r'api/questions', QuestionViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^q/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^answer/(?P<question_id>\d+)/$', views.answer, name='answer'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^add/$', views.add, name='add'),
    url(r'^answer/$', views.add_answer, name='add_answer'),
    url(r'^vote/(?P<user_id>\d+)/(?P<answer_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.vote, name='vote'),
    url(r'^comment/(?P<answer_id>\d+)/$', views.comment, name='comment'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tag/(?P<tag>\w+)/$', views.tag, name='tag'),
    url(r'^thumb/(?P<user_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.thumb, name='thumb'),
    url('^markdown/', include( 'django_markdown.urls')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    #url('^forgot/', include('password_reset.urls')),
]

tasks/urls.py
# coding=utf-8
from django.conf.urls import url
from tasks import views

urlpatterns = [
    url(r'^(?P<patient_id>[0-9]+)/edit/$', views.TherapistTaskView.as_view(), name='create'),
    url(r'^complete/$', views.PatientTaskView.as_view(), name='complete'),
]

tasks/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from authenticate.models import UserProfile
from authenticate.models import Therapist


class MainTask(models.Model):
    therapist = models.ForeignKey(Therapist)
    patient = models.ForeignKey(UserProfile)
    title = models.CharField(max_length=30, blank=False, null=False)
    task = models.TextField()
    deadline = models.DateTimeField()
    completed = models.BooleanField(default=False)
    completed_on = models.DateTimeField(null=True, blank=True)
    # created = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(blank=False, null=False)

    def __unicode__(self):
        return self.patient.user.username + ' ' + self.title + ' completed: ' + str(self.completed)

    def as_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'completed': self.completed,
            'completed_on': str(self.completed_on),
            'created': str(self.created)
        }


class SubTask(models.Model):
    order = models.PositiveSmallIntegerField()
    main_task = models.ForeignKey(MainTask)
    task = models.TextField()
    completed = models.BooleanField(default=False)
    completed_on = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.task

tasks/forms.py
# coding=utf-8
from django import forms
from tasks import models


class MainTaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(input_formats=['%d-%m-%Y %H:%M'])

    class Meta(object):
        model = models.MainTask
        fields = ('title', 'task', 'deadline')

tasks/views.py
# coding=utf-8
import json
from django.shortcuts import render
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils.timezone import datetime
from django.http import HttpResponseRedirect, HttpResponse

from authenticate.models import Therapist, UserProfile
from tasks.models import MainTask
from tasks import forms


class TherapistTaskView(View):
    @method_decorator(login_required)
    def get(self, request, patient_id):
        return render(request, 'tasks/create-task.html',
                      {'tasks': MainTask.objects.filter(patient__user_id=patient_id)})

    @method_decorator(login_required)
    def post(self, request, patient_id):
        task_form = forms.MainTaskForm(request.POST)
        if task_form.is_valid():
            task = task_form.save(commit=False)
            task.therapist = Therapist.objects.get(user_profile__user=request.user.id)
            task.patient = UserProfile.objects.get(user_id=patient_id)
            task.created = datetime.now()
            task.save()
        else:
            print task_form.errors
        return HttpResponseRedirect('')


class PatientTaskView(View):
    @method_decorator(login_required)
    def get(self, request):
        # user = UserProfile.objects.
        return render(request, 'tasks/complete-task.html',
                      {'tasks': MainTask.objects.filter(patient__user_id=request.user.id)[:4]})

    @method_decorator(login_required)
    def post(self, request):
        if 'toggle' in request.POST:
            task = MainTask.objects.get(id=int(request.POST['task']), patient__user_id=request.user.id)
            if task.completed:
                task.completed = False
            else:
                task.completed = True
            task.completed_on = datetime.now()
            task.save()
            return HttpResponse(json.dumps({'state': task.completed}))

templates/tasks/complete-task.html
{% extends "core/dashboard/base-patient-dash.html" %}
{% load staticfiles %}
{% block title %}Create Homework{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/DateTimePicker.min.css' %}">
{% endblock %}
{% block body %}
    <div class="">
        <div class="row">
            <div class="col-sm-12" id="task-feed">
                {% for task in tasks %}
                    {% if not task.completed %}
                        <div class="row" id="task-{{ task.id }}">
                            <div class="card card-block">
                                <h3 class="card-title">
                                    {{ task.title }}
                                    <span class="btn btn-secondary task-toggle pull-right"
                                          data-task-id="{{ task.id }}">Mark complete</span></h3>
                                <p class="card-text">
                                    <span class="label label-info">Due {{ task.deadline }}</span>
                                    <br>
                                    {{ task.task }}
                                </p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js_scripts %}
    <script type="application/javascript">
        $(document).ready(function () {
            var noTaskCard = '<div class="row" id="empty-task">' +
                    '<div class="card card-block">' +
                    ' <h3 class="card-title">All tasks complete!</h3>' +
                    '<p class="card-text">Your therapist has not added any new tasks for you to complete.</p>' +
                    '</div></div>';
            var checkTaskFeed = function () {
                var taskFeed = $('#task-feed').find('> div');
                if (taskFeed.length === 0) {
                    $('#task-feed').append(noTaskCard);
                } else {
                    $('#empty-task').hide();
                }
            };
            $('#tasksSidebar').addClass('active');
            checkTaskFeed();
            $('.task-toggle').on('click', function (e) {
                var that = $(this);
                $.ajax({
                    url: '{% url 'tasks:complete' %}',
                    method: 'post',
                    dataType: 'json',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'task': that.attr('data-task-id'),
                        'toggle': true
                    },
                    success: function (data) {
                        if (data.state) {
                            $('#task-' + that.attr('data-task-id')).remove();
                        }
                        checkTaskFeed();
                    },
                    error: function (err) {
                        console.log(err);
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/tasks/create-task.html
{% extends "core/therapist-dashboard/base-therapist-dash.html" %}
{% load static from staticfiles %}
{% block title %}Create Homework{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/DateTimePicker.min.css' %}">
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <a class="btn btn-primary" href="" id="addTask">Add task</a>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <form id="newTaskForm" method="post">
                        {% csrf_token %}
                        <div class="card card-block">
                            <div class="card-title">
                                <label for="titleInput">Enter a title for this task.</label>
                                <input id="titleInput" type="text" name="title" class="form-control" required>
                            </div>
                            <p class="card-text">
                                <label for="taskInput">Enter the task</label>
                                <textarea id="taskInput" name="task" class="form-control" required></textarea>
                            </p>
                            <div class="row">
                                <div class="col-sm-4">
                                    <label for="deadlineInput">Deadline</label>
                                    <input class="form-control" id="deadlineInput" name="deadline" type="text"
                                           data-field="datetime"
                                           readonly required>
                                    <div id="dtBox"></div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="submit" class="btn btn-success" value="Add">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                {% for task in tasks %}
                    <div class="row">
                        <div class="card card-block">
                            <h3 class="card-title"><span
                                    class="fa fa-pencil-square-o text-muted"></span> {{ task.title }}</h3>
                            <p class="card-text">
                                <span class="label label-info">Due {{ task.deadline }}</span>
                                <br>
                                {{ task.task }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-sm-4">

            </div>
        </div>
    </div>
{% endblock %}

{% block js_scripts %}
    <script type="application/javascript" src="{% static 'js/DateTimePicker.min.js' %}"></script>
    <script type="application/javascript">
        $(document).ready(function () {
            var newTaskForm = $('#newTaskForm');
            var dtp = $('#dtBox').DateTimePicker({
                settingValueOfElement: function () {
                    $('#deadlineInput').val(this.getDateTimeStringInFormat());
                }
            });
            newTaskForm.hide();
            $('#addTask').on('click', function (e) {
                newTaskForm.toggle();
                {#                if (newTaskForm.is(':visible')){#}
                {#                    this.text('Hide task');#}
                {#                } else {#}
                {#                    this.text('Add task');#}
                {#                }#}
                e.preventDefault();
            });
            {#            $.ajax({#}
            {#                url: '{% url 'tasks:create' %}',#}
            {#                method: 'post',#}
            {#                data: {#}
            {#                    #}
            {#                },#}
            {#                dataType: 'json',#}
            {#                accept: function (msg) {#}
            {#                    console.log(msg);#}
            {#                },#}
            {#                error: function(err){#}
            {#                    console.log(err);#}
            {#                }#}
            {#            });#}
        });
    </script>
{% endblock %}