core/urls.py
# coding=utf-8
"""
URLs for core app
"""

from django.conf.urls import url
from core import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^progress/check/$', views.progress_delay, name='progress_check'),
    url(r'^patient/$', views.PatientHomeView.as_view(), name='patient_home'),
    url(r'^therapist/$', views.therapist_home, name='therapist_home'),
    url(r'^therapist/patient/$', views.patient_list, name='patient_list'),
    url(r'^therapist/patient/(?P<patient_id>[0-9]+)/$', views.patient_list, name='patient_profile'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
]

gleam/urls.py
# coding=utf-8
"""gleam URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from diagnostic import urls as diagnostic_urls
from authenticate import urls as auth_urls
from core import urls as core_urls
from journal import urls as journal_urls
from chat import urls as chat_urls
from tasks import urls as tasks_urls

urlpatterns = [
    url(r'', include(core_urls, namespace='core')),
    url(r'^users/', include(auth_urls, namespace='authenticate')),
    url(r'^survey/', include(diagnostic_urls, namespace='diagnostic')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^qa/', include(qa_urls, namespace='qa')),
    # url(r'^case/', include(cc_urls, namespace='case')),
    url(r'^journal/', include(journal_urls, namespace='journal')),
    url(r'^chat/', include(chat_urls, namespace='chat')),
    url(r'^tasks/', include(tasks_urls, namespace='tasks'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from qa import views

from django.conf.urls import url, include
from django.contrib.auth.models import User
from qa.models import Question, Tag
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

class QuestionSerializer(serializers.HyperlinkedModelSerializer):
    tags = serializers.SlugRelatedField(
        many=True,
        read_only=True,
        slug_field='slug'
     )
    class Meta:
        model = Question
        fields = ('id', 'pub_date', 'question_text', 'tags', 'views')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'api/users', UserViewSet)
router.register(r'api/questions', QuestionViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^q/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^answer/(?P<question_id>\d+)/$', views.answer, name='answer'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^add/$', views.add, name='add'),
    url(r'^answer/$', views.add_answer, name='add_answer'),
    url(r'^vote/(?P<user_id>\d+)/(?P<answer_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.vote, name='vote'),
    url(r'^comment/(?P<answer_id>\d+)/$', views.comment, name='comment'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tag/(?P<tag>\w+)/$', views.tag, name='tag'),
    url(r'^thumb/(?P<user_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.thumb, name='thumb'),
    url('^markdown/', include( 'django_markdown.urls')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    #url('^forgot/', include('password_reset.urls')),
]

core/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User


class ProgressIssue(models.Model):
    """
    Model to gather stats on issues that hinder a user's progress in their regime
    """
    user = models.ForeignKey(User)

    work = models.BooleanField(default=False, blank=True)
    access_to_computer = models.BooleanField(default=False, blank=True)
    time_commitment = models.BooleanField(default=False, blank=True)
    motivation = models.BooleanField(default=False, blank=True)
    forgetfulness = models.BooleanField(default=False, blank=True)
    tired = models.BooleanField(default=False, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)

    class Meta(object):
        unique_together = ('user', 'created_on',)

core/forms.py
# coding=utf-8

from core import models
from django import forms


class ProgressIssueForm(forms.ModelForm):
    class Meta(object):
        model = models.ProgressIssue
        exclude = ('user',)

core/views.py
# coding=utf-8
import json
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.utils.timezone import datetime
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from core import forms
from tasks.models import MainTask
from journal.models import Entry, Note
from authenticate.models import Client

MAX_ROWS = 5


def index(request):
    return render(request, 'index.html', {})


@login_required()
def progress_delay(request):
    if request.method == 'POST':
        progress_issue = forms.ProgressIssueForm(request.POST)
        if progress_issue.is_valid():
            progress_issue = progress_issue.save(commit=False)
            progress_issue.user = User.objects.get(id=request.user.id)
            progress_issue.save()
            if request.GET.get('courses', None) is not None:
                return HttpResponseRedirect(reverse('case:start_course'))
            else:
                print request.GET
                return HttpResponseRedirect('/')
        else:
            return render(request, 'core/progress-delay.html', {'errors': progress_issue.errors})
    else:
        return render(request, 'core/progress-delay.html', {})


@login_required()
def therapist_home(request):
    # TODO order clients by last appointment/different metric
    return render(request, 'core/therapist-dashboard/content-tp-dash.html', {
        'notes': Note.objects.filter(therapist__user_profile__user_id=request.user.id)[:MAX_ROWS],
        'clients': Client.objects.filter(therapist__user_profile__user_id=request.user.id)[:MAX_ROWS]
    })


def landing(request):
    return render(request, 'core/landing/landing.html', {})


class PatientHomeView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'core/dashboard/patient-home.html',
                      {'tasks': MainTask.objects.filter(patient__user_id=request.user.id, completed=False).order_by(
                          'created')[:MAX_ROWS],
                       'journals': Entry.objects.filter(user_id=request.user.id).order_by('-created')[:MAX_ROWS]
                       })

    @method_decorator(login_required)
    def post(self, request):
        if 'toggle' in request.POST:
            task = MainTask.objects.get(id=int(request.POST['task']), patient__user_id=request.user.id)
            if task.completed:
                task.completed = False
            else:
                task.completed = True
            task.completed_on = datetime.now()
            task.save()
            tasks = MainTask.objects.filter(patient__user_id=request.user.id, completed=False).order_by('created')[
                    :MAX_ROWS]
            return HttpResponse(json.dumps(
                {'state': task.completed,
                 'tasks': [task.as_dict() for task in tasks]
                 }))


@login_required()
def dashboard(request):
    if request.user.userprofile.is_therapist:
        return therapist_home(request)
    else:
        return PatientHomeView.as_view()(request)


@login_required()
def patient_list(request):
    client_list = Client.objects.filter(therapist__user_profile__user_id=request.user.id)
    paginator = Paginator(client_list, MAX_ROWS)
    try:
        clients = paginator.page(request.GET.get('page'))
    except PageNotAnInteger:
        clients = paginator.page(1)
    except EmptyPage:
        clients = paginator.page(paginator.num_pages)
    return render(request, 'therapist/patient-list.html',
                  {'clients': clients,
                   'paginator': paginator})

templates/core/landing/landing.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Gleam</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'css/landing_css/animate.min.css' %}">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'css/landing_css/bootstrap.min.css' %}">
    <!-- font-awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- google font -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/landing_css/templatemo-style.css' %}">

</head>
<body>
<!-- start preloader -->
<div class="preloader">
    <div class="sk-spinner sk-spinner-rotating-plane"></div>
</div>
<!-- end preloader -->
<!-- start navigation -->
<nav class="navbar navbar-default navbar-fixed-top templatemo-nav" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand"><img src="{% static 'images/gleam-124.png' %}"> </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right text-uppercase">
                <li><a href="#home">Home</a></li>
                <li><a href="#features">Features</a>
                    <ul>
                        <li><a href="#tpfeatures">Therapist Features</a></li>
                        <li><a href="#patientfeatures">Patient Features</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- end navigation -->
<!-- start home -->
<section id="home">
    <div class="overlay">
        <div class="container">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10 wow fadeIn" data-wow-delay="0.3s">
                    <h1 class="text-upper">Gleam</h1>
                    <p class="tm-white">Gleam is a secure, HIPAA compliant platform that facilitates the therapeutic
                        process and centralizes patient and therapist interactions in between appointments</p>
                    <img src="{% static 'images/landing_images/software-img.png' %}" class="img-responsive"
                         alt="home img">
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>
</section>
<!-- end home -->
<!-- start divider -->
<section id="divider">
    <section id="features">
        <div class="container">
            <div class="row">
                <div class="col-md-4 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                    <i class="fa fa-laptop"></i>
                    <h3 class="text-uppercase">COPING EXERCISES</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore
                        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation. </p>
                </div>
                <div class="col-md-4 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                    <i class="fa fa-twitter"></i>
                    <h3 class="text-uppercase">CENTRALIZED COMMUNICATION</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore
                        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation. </p>
                </div>
                <div class="col-md-4 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                    <i class="fa fa-font"></i>
                    <h3 class="text-uppercase">PROGRESS TRACKING AND ANALYSIS</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore
                        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation. </p>
                </div>
            </div>
        </div>
    </section>
</section>
<!-- end divider -->

<!-- start feature -->
<section id="feature">
    <section id="tpfeatures">
        <div class="container">
            <div class="row">
                <div class="col-md-6 wow fadeInLeft" data-wow-delay="0.6s">
                    <h2 class="text-uppercase">Our Software Features</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore
                        et dolore magna aliqua.</p>
                    <p><span><i class="fa fa-mobile"></i></span>Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit,
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p><i class="fa fa-code"></i>Quis autem velis reprehenderit et quis voluptate velit esse quam.</p>
                </div>
                <div class="col-md-6 wow fadeInRight" data-wow-delay="0.6s">
                    <img src="{% static 'images/landing_images/software-img.png' %}" class="img-responsive"
                         alt="feature img">
                </div>
            </div>
        </div>
    </section>
</section>
<!-- end feature -->

<!-- start feature1 -->
<section id="feature1">
    <section id="patientfeatures">
        <div class="container">
            <div class="row">
                <div class="col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                    <img src="{% static 'images/landing_images/software-img.png' %}" class="img-responsive"
                         alt="feature img">
                </div>
                <div class="col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                    <h2 class="text-uppercase">More of Your Software</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore
                        et dolore magna aliqua.</p>
                    <p><span><i class="fa fa-mobile"></i></span>Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit,
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p><i class="fa fa-code"></i>Quis autem velis reprehenderit et quis voluptate velit esse quam.</p>
                </div>
            </div>
        </div>
    </section>
</section>
<!-- end feature1 -->

<!-- start pricing
<section id="pricing">
    <div class="container">
        <div class="row">
            <div class="col-md-12 wow bounceIn">
                <h2 class="text-uppercase">Our Pricing</h2>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-delay="0.6s">
                <div class="pricing text-uppercase">
                    <div class="pricing-title">
                        <h4>Basic Plan</h4>
                        <p>$11</p>
                        <small class="text-lowercase">monthly</small>
                    </div>
                    <ul>
                        <li>6 GB Space</li>
                        <li>600 GB Bandwidth</li>
                        <li>60 More Themes</li>
                        <li>Lifetime Support</li>
                    </ul>
                    <button class="btn btn-primary text-uppercase">Sign up</button>
                </div>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-delay="0.6s">
                <div class="pricing active text-uppercase">
                    <div class="pricing-title">
                        <h4>Business Plan</h4>
                        <p>$22</p>
                        <small class="text-lowercase">monthly</small>
                    </div>
                    <ul>
                        <li>15 GB space</li>
                        <li>1,500 GB Bandwidth</li>
                        <li>150 More Themes</li>
                        <li>Lifetime Support</li>
                    </ul>
                    <button class="btn btn-primary text-uppercase">Sign up</button>
                </div>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-delay="0.6s">
                <div class="pricing text-uppercase">
                    <div class="pricing-title">
                        <h4>Pro Plan</h4>
                        <p>$33</p>
                        <small class="text-lowercase">monthly</small>
                    </div>
                    <ul>
                        <li>35 GB space</li>
                        <li>3,500 GB bandwidth</li>
                        <li>350 more themes</li>
                        <li>Lifetime Support</li>
                    </ul>
                    <button class="btn btn-primary text-uppercase">Sign Up</button>
                </div>
            </div>
        </div>
    </div>
</section>
end pricing -->

<!-- start download -->
<section id="feature">
    <div class="container" style="text-align:center">
        <div class="row">
            <h2 class="text-uppercase" style="text-align:center">Login to Your Profile</h2><br>
            <div class="col-md-6 wow fadeInLeft" data-wow-delay="0.6s">
                <button class="btn btn-primary text-uppercase"><i class="fa fa-download"></i>
                    <a href="{% url 'core:therapist_home' %}" style="color:white">Therapist</a></button>
            </div>
            <div class="col-md-6 wow fadeInRight" data-wow-delay="0.6s">
                <button class="btn btn-primary text-uppercase"><i class="fa fa-download"></i>
                    <a href="{% url 'core:patient_home' %}" style="color:white">Patient</a></button>
            </div>
        </div>
    </div>
</section>
<!-- end download -->

<!-- start contact
<section id="contact">
    <div class="overlay">
        <div class="container">
            <div class="row">
                <div class="col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                    <h2 class="text-uppercase">Contact Us</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation. </p>
                    <address>
                        <p><i class="fa fa-map-marker"></i>36 Street Name, City Name, United States</p>
                        <p><i class="fa fa-phone"></i> 010-010-0110 or 020-020-0220</p>
                        <p><i class="fa fa-envelope-o"></i> info@company.com</p>
                    </address>
                </div>
                <div class="col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                    <div class="contact-form">
                        <form action="#" method="post">
                            <div class="col-md-6">
                                <input type="text" class="form-control" placeholder="Name">
                            </div>
                            <div class="col-md-6">
                                <input type="email" class="form-control" placeholder="Email">
                            </div>
                            <div class="col-md-12">
                                <input type="text" class="form-control" placeholder="Subject">
                            </div>
                            <div class="col-md-12">
                                <textarea class="form-control" placeholder="Message" rows="4"></textarea>
                            </div>
                            <div class="col-md-8">
                                <input type="submit" class="form-control text-uppercase" value="Send">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
end contact -->

<!-- start footer -->
<footer>
    <div class="container">
        <div class="row">
            <p>Copyright © 2016 Gleam</p>
        </div>
    </div>
</footer>
<!-- end footer -->

<script src="{% static 'js/jquery-latest.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/landing_js/wow.min.js' %}"></script>
<script src="{% static 'js/landing_js/jquery.singlePageNav.min.js' %}"></script>
<script src="{% static 'js/landing_js/custom.js' %}"></script>
</body>
</html>